# Test 2023-07-08 at 00:52:14

name: Test

on:
  push:
    paths:
      - '**.pm'
      - '**pushToGitHub.pl'
      - '**.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Successfull call
      run:  python3 -m sound.formats.mp3

    - name: Error call - wrong start folder
      if: ${{ always() }}
      run:  python3 sound/formats/mp3.py || true

    - name: Error call - no package established
      if: ${{ always() }}
      run:  (cd sound/formats; python3 mp3.py) || true

    - name: Error call - ImportError
      if: ${{ always() }}
      run:  (cd sound/formats; python3 -m mp3) || true
